"""Audit directly rendered publication single figures.

This checker is for figures generated by experiment scripts into
``single_figures`` directories. It intentionally does not inspect the legacy
standardized crop exports.
"""

from __future__ import annotations

import csv
import re
from pathlib import Path

import pandas as pd

import figure_style


PROJECT_ROOT = Path(__file__).resolve().parents[1]
RESULTS_ROOT = PROJECT_ROOT / "results"
OUTPUT_ROOT = RESULTS_ROOT / "publication_single_figures_audit"
STYLE_CONFIG = PROJECT_ROOT / "configs" / "figure_style.yaml"


def single_pngs() -> list[Path]:
    return sorted(
        path
        for path in RESULTS_ROOT.rglob("single_figures/*.png")
        if "standardized_single_panels" not in path.parts
    )


def paired_pdf_exists(path: Path) -> bool:
    return path.with_suffix(".pdf").exists()


def audit_rows(paths: list[Path]) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    config = {"plot_style_config": str(STYLE_CONFIG)}
    for path in paths:
        rendered = figure_style.audit_rendered_png(path, config)
        relative = path.relative_to(PROJECT_ROOT)
        name = path.name
        warnings = []
        if re.search(r"__P\d+", name):
            warnings.append("generic_panel_label_in_filename")
        if "PACA" in str(relative).upper():
            warnings.append("paca_reference")
        if not paired_pdf_exists(path):
            warnings.append("missing_pdf_pair")
        rows.append(
            {
                "path": str(relative),
                "width_px": rendered["width_px"],
                "height_px": rendered["height_px"],
                "aspect_ratio": rendered["aspect_ratio"],
                "content_fraction": rendered["content_fraction"],
                "edge_ink_max": rendered["edge_ink_max"],
                "render_status": rendered["status"],
                "render_warnings": rendered["warnings"],
                "pdf_pair": paired_pdf_exists(path),
                "filename_status": "PASS" if not warnings else "WARN",
                "filename_warnings": ";".join(warnings),
                "status": "PASS"
                if rendered["status"] == "PASS" and not warnings
                else "WARN",
            }
        )
    return rows


def write_tsv(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]), delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)


def write_report(rows: list[dict[str, object]]) -> None:
    df = pd.DataFrame(rows)
    total = len(df)
    pass_count = int(df["status"].eq("PASS").sum()) if total else 0
    warn = df[df["status"].ne("PASS")] if total else pd.DataFrame()
    lines = [
        "# Publication Single-Figure Audit",
        "",
        "Scope: direct outputs from experiment scripts under `single_figures/`.",
        "Legacy crop-based exports are intentionally excluded.",
        "",
        f"- Total PNG figures: {total}",
        f"- PASS: {pass_count}",
        f"- WARN: {total - pass_count}",
        f"- Missing PDF pairs: {int((~df['pdf_pair']).sum()) if total else 0}",
        f"- Generic Pxx filename labels: {int(df['path'].str.contains(r'__P\\d+', regex=True).sum()) if total else 0}",
        f"- PACA references: {int(df['path'].str.contains('PACA', case=False, regex=False).sum()) if total else 0}",
        "",
    ]
    if not warn.empty:
        lines.extend(["## Warnings", ""])
        for row in warn.itertuples(index=False):
            details = "; ".join(
                item
                for item in [
                    str(row.render_warnings or ""),
                    str(row.filename_warnings or ""),
                ]
                if item
            )
            lines.append(f"- `{row.path}`: {details}")
        lines.append("")
    lines.extend(
        [
            "## Policy",
            "",
            "- These files are generated directly by experiment plotting code.",
            "- They should not contain panel letters such as A/B/C/D.",
            "- Figure-level titles should be left to the final manuscript layout.",
            "- Axis labels, compact legends and scientifically necessary scale bars are retained.",
        ]
    )
    (OUTPUT_ROOT / "publication_single_figures_audit.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def main() -> None:
    paths = single_pngs()
    rows = audit_rows(paths)
    write_tsv(OUTPUT_ROOT / "publication_single_figures_audit.tsv", rows)
    write_report(rows)
    print(f"single_figures={len(rows)}")
    print(f"warnings={sum(row['status'] != 'PASS' for row in rows)}")


if __name__ == "__main__":
    main()
